# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './Visual/widget_cliente.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_widget_cliente(object):
    def setupUi(self, widget_cliente):
        widget_cliente.setObjectName("widget_cliente")
        widget_cliente.resize(349, 266)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(widget_cliente.sizePolicy().hasHeightForWidth())
        widget_cliente.setSizePolicy(sizePolicy)
        self.verticalLayout = QtWidgets.QVBoxLayout(widget_cliente)
        self.verticalLayout.setObjectName("verticalLayout")
        self.boton_guardar = QtWidgets.QPushButton(widget_cliente)
        self.boton_guardar.setObjectName("boton_guardar")
        self.verticalLayout.addWidget(self.boton_guardar)
        self.boton_eliminar = QtWidgets.QPushButton(widget_cliente)
        self.boton_eliminar.setObjectName("boton_eliminar")
        self.verticalLayout.addWidget(self.boton_eliminar)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label_1 = QtWidgets.QLabel(widget_cliente)
        self.label_1.setObjectName("label_1")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_1)
        self.label_2 = QtWidgets.QLabel(widget_cliente)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.label_3 = QtWidgets.QLabel(widget_cliente)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.label_4 = QtWidgets.QLabel(widget_cliente)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.label_5 = QtWidgets.QLabel(widget_cliente)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.cubiertos = QtWidgets.QVBoxLayout()
        self.cubiertos.setObjectName("cubiertos")
        self.formLayout.setLayout(4, QtWidgets.QFormLayout.FieldRole, self.cubiertos)
        self.nombre = QtWidgets.QLineEdit(widget_cliente)
        self.nombre.setObjectName("nombre")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.nombre)
        self.apellido = QtWidgets.QLineEdit(widget_cliente)
        self.apellido.setObjectName("apellido")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.apellido)
        self.dire = QtWidgets.QLineEdit(widget_cliente)
        self.dire.setObjectName("dire")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.dire)
        self.tel = QtWidgets.QLineEdit(widget_cliente)
        self.tel.setObjectName("tel")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.tel)
        self.horizontalLayout.addLayout(self.formLayout)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(widget_cliente)
        QtCore.QMetaObject.connectSlotsByName(widget_cliente)

    def retranslateUi(self, widget_cliente):
        _translate = QtCore.QCoreApplication.translate
        widget_cliente.setWindowTitle(_translate("widget_cliente", "Form"))
        self.boton_guardar.setText(_translate("widget_cliente", "Guardar"))
        self.boton_eliminar.setText(_translate("widget_cliente", "Eliminar Cliente"))
        self.label_1.setText(_translate("widget_cliente", "Nombre"))
        self.label_2.setText(_translate("widget_cliente", "Apellido"))
        self.label_3.setText(_translate("widget_cliente", "Dirección"))
        self.label_4.setText(_translate("widget_cliente", "Teléfono"))
        self.label_5.setText(_translate("widget_cliente", "Cubiertos"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    widget_cliente = QtWidgets.QWidget()
    ui = Ui_widget_cliente()
    ui.setupUi(widget_cliente)
    widget_cliente.show()
    sys.exit(app.exec_())
