# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './Visual/widget_pedido.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_widget_pedido(object):
    def setupUi(self, widget_pedido):
        widget_pedido.setObjectName("widget_pedido")
        widget_pedido.resize(134, 233)
        self.verticalLayout = QtWidgets.QVBoxLayout(widget_pedido)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.groupbox = QtWidgets.QGroupBox(widget_pedido)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupbox.sizePolicy().hasHeightForWidth())
        self.groupbox.setSizePolicy(sizePolicy)
        self.groupbox.setMaximumSize(QtCore.QSize(150, 250))
        self.groupbox.setObjectName("groupbox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupbox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label_cliente = QtWidgets.QLabel(self.groupbox)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_cliente.setFont(font)
        self.label_cliente.setText("")
        self.label_cliente.setObjectName("label_cliente")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_cliente)
        self.boton_eliminar = QtWidgets.QPushButton(self.groupbox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.boton_eliminar.sizePolicy().hasHeightForWidth())
        self.boton_eliminar.setSizePolicy(sizePolicy)
        self.boton_eliminar.setMaximumSize(QtCore.QSize(25, 25))
        self.boton_eliminar.setObjectName("boton_eliminar")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.boton_eliminar)
        self.verticalLayout_2.addLayout(self.formLayout)
        self.lista_ing = QtWidgets.QListWidget(self.groupbox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lista_ing.sizePolicy().hasHeightForWidth())
        self.lista_ing.setSizePolicy(sizePolicy)
        self.lista_ing.setMaximumSize(QtCore.QSize(110, 110))
        self.lista_ing.setObjectName("lista_ing")
        self.verticalLayout_2.addWidget(self.lista_ing)
        self.label_cubierto = QtWidgets.QLabel(self.groupbox)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_cubierto.setFont(font)
        self.label_cubierto.setText("")
        self.label_cubierto.setObjectName("label_cubierto")
        self.verticalLayout_2.addWidget(self.label_cubierto)
        self.label_precio = QtWidgets.QLabel(self.groupbox)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_precio.setFont(font)
        self.label_precio.setText("")
        self.label_precio.setObjectName("label_precio")
        self.verticalLayout_2.addWidget(self.label_precio)
        self.horizontalLayout.addWidget(self.groupbox)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(widget_pedido)
        QtCore.QMetaObject.connectSlotsByName(widget_pedido)

    def retranslateUi(self, widget_pedido):
        _translate = QtCore.QCoreApplication.translate
        widget_pedido.setWindowTitle(_translate("widget_pedido", "Form"))
        self.boton_eliminar.setText(_translate("widget_pedido", "X"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    widget_pedido = QtWidgets.QWidget()
    ui = Ui_widget_pedido()
    ui.setupUi(widget_pedido)
    widget_pedido.show()
    sys.exit(app.exec_())
